[
  {
    "serial_no": "245V-EAZS",
    "name": "Voltas 1.5 Ton 3 Star Split AC",
    "price": "55000",
    "rating_stars": 4.5,
    "rating_source_icon": "img/OCOL/amazon.png",
    "type": "AC",
    "AC-TR": 1.5,
    "AC-Type": "Split",
    "AC-STAR": 3,
    "description": "A high-performance split AC from Voltas, perfect for medium-sized rooms, featuring a 3-star energy rating for efficient cooling. Includes a 1-year comprehensive warranty on the product and 5-year warranty on the compressor.",
    "has_size_option": false,
    "available_sizes": null,
    "price_size": null
  },
  {
    "serial_no": "987H-INV5",
    "name": "Hitachi 2.0 Ton 5 Star Inverter AC",
    "price": "72000",
    "rating_stars": 4.8,
    "rating_source_icon": "img/OCOL/indiamart.png",
    "type": "AC",
    "AC-TR": 2.0,
    "AC-Type": "Inverter Split",
    "AC-STAR": 5,
    "description": "Experience superior cooling and energy savings with Hitachi's 5-star inverter AC, designed for larger spaces. Features a copper condenser for better heat transfer and durability. Smart diagnostic features included.",
    "has_size_option": true,
    "available_sizes": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "price_size": "AU"
  },
  {
    "serial_no": "321D-WNDO",
    "name": "Daikin 1.0 Ton 3 Star Window AC",
    "price": "38000",
    "rating_stars": 4.0,
    "rating_source_icon": "img/OCOL/amazon.png",
    "type": "AC",
    "AC-TR": 1.0,
    "AC-Type": "Window",
    "AC-STAR": 3,
    "description": "Compact and efficient window AC from Daikin, ideal for smaller rooms, offering reliable cooling performance. Easy installation and maintenance. Suitable for residential use.",
    "has_size_option": false,
    "available_sizes": null,
    "price_size": null
  },
  {
    "serial_no": "550S-QLED",
    "name": "Samsung 55 Inch QLED Smart TV",
    "price": "77000",
    "rating_stars": 4.7,
    "rating_source_icon": "img/OCOL/amazon.png",
    "type": "TV",
    "AC-TR": null,
    "AC-Type": null,
    "AC-STAR": null,
    "description": "Stunning 4K QLED display with smart features for an immersive entertainment experience. Comes with built-in voice assistant and multiple HDMI ports for connectivity.",
    "has_size_option": true,
    "available_sizes": [1, 2, 3, 4, 5],
    "price_size": [77000, 80000, 83000, 86000, 89000]
  },
  {
    "serial_no": "123L-REF",
    "name": "LG 260L Double Door Refrigerator",
    "price": "32500",
    "rating_stars": 4.2,
    "rating_source_icon": "img/OCOL/amazon.png",
    "type": "Refrigerator",
    "AC-TR": null,
    "AC-Type": null,
    "AC-STAR": null,
    "description": "Spacious and energy-efficient refrigerator with advanced cooling technology. Features a multi-air flow system and smart inverter compressor for silent operation and energy savings.",
    "has_size_option": false,
    "available_sizes": null,
    "price_size": null
  },
  {
    "serial_no": "678V-TWR",
    "name": "Voltas 2.0 Ton 4 Star Tower AC",
    "price": "80000",
    "rating_stars": 4.1,
    "rating_source_icon": "img/OCOL/indiamart.png",
    "type": "AC",
    "AC-TR": 2.0,
    "AC-Type": "Tower",
    "AC-STAR": 4,
    "description": "Elegant and powerful tower AC from Voltas, perfect for large living rooms or offices. Provides quick cooling and has a sleek design that blends well with modern interiors. Remote control included.",
    "has_size_option": true,
    "available_sizes": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "price_size": "AU"
  },
  {
    "serial_no": "100S-WASH",
    "name": "Samsung 7.5 kg Fully Automatic Washing Machine",
    "price": "28000",
    "rating_stars": 4.3,
    "rating_source_icon": "img/OCOL/amazon.png",
    "type": "Washing Machine",
    "AC-TR": null,
    "AC-Type": null,
    "AC-STAR": null,
    "description": "Efficient and easy-to-use washing machine with multiple wash programs for different fabric types. Features a diamond drum for gentle fabric care and a digital inverter motor for quiet and durable performance.",
    "has_size_option": false,
    "available_sizes": null,
    "price_size": null
  },
  {
    "serial_no": "777M-OVEN",
    "name": "LG 28L Convection Microwave Oven",
    "price": "15000",
    "rating_stars": 4.6,
    "rating_source_icon": "img/OCOL/amazon.png",
    "type": "Microwave Oven",
    "AC-TR": null,
    "AC-Type": null,
    "AC-STAR": null,
    "description": "Versatile microwave oven for baking, grilling, and reheating. Comes with a wide range of auto-cook menus and a child lock feature for safety.",
    "has_size_option": false,
    "available_sizes": null,
    "price_size": null
  },
  {
    "serial_no": "D318PCCIBS",
    "name": "Hitachi 1.5 Ton 3 Star 2025",
    "price": "36990",
    "rating_stars": 4,
    "rating_source_icon": "img/OCOL/filpkart.png",
    "type": "AC",
    "AC-TR": 1.5,
    "AC-Type": "Split",
    "AC-STAR": 3,
    "description": "Enjoy better airflow with 4-Way Swing (upgraded from 2024). Features ice Clean (FrostWash) for cleaner air and Penta Sensor for smart cooling. Benefit from convenient features like Filter Clean Indicator and Long Air Throw. Built for hot weather (up to 52°C) with a durable 100% Copper condenser.",
    "has_size_option": false,
    "available_sizes": null,
    "price_size": null
  },
  {
    "serial_no": "QA55QE1CAKLXL",
    "name": "SAMSUNG 55INCH QLED Q60C",
    "price": "65000",
    "rating_stars": 4.5,
    "rating_source_icon": "img/OCOL/filpkart.png",
    "type": "TV",
    "unit": "pcs",
    "AC-TR": null,
    "AC-Type": null,
    "AC-STAR": null,
    "description": "No description available."
  },
  {
    "serial_no": "FTKL71UV",
    "name": "SPLIT AC DAIKIN 2.0 TON 3 STAR - INVERTER AC",
    "price": "50500",
    "rating_stars": 0.0,
    "rating_source_icon":
      "img/OCOL/none.png",
    "type": "AC",
    "unit": "pcs",
    "AC-TR": 2.0,
    "AC-Type": "split",
    "AC-STAR": 3,
    "description": "No description available."
  }
]
